name: CI

on:
  push
  pull_request

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/cargo@v1
        with:
         command: clippy

  build-linux:
    runs-on: ubuntu-latest
    needs: test-linux
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build app
        uses: actions-rs/cargo@v1
        with:
          command: build
      - uses: actions/upload-artifact@v1
        with:
          name: tic-tac-toe-linux
          path: target/debug/tic-tac-toe-rust

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/cargo@v1
        with:
          command: clippy

  build-windows:
    runs-on: windows-latest
    needs: test-windows
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build app
        uses: actions-rs/cargo@v1
        with:
          command: build
      - uses: actions/upload-artifact@v1
        with:
          name: tic-tac-toe-windows
          path: target/debug/tic-tac-toe-rust.exe
